% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={MTH6139 Time Series},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{MTH6139 Time Series}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Analysing Petrol Prices Over Time in the UK}
\author{true}
\date{13 March 2024}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{analysing-petrol-prices-in-the-uk-over-time-using-prophet}{%
\section{Analysing Petrol Prices in the UK Over Time Using
Prophet}\label{analysing-petrol-prices-in-the-uk-over-time-using-prophet}}

This project explores Petrol price dynamics using time series analysis
techniques. The data used for this analysis is downloaded from
\href{https://www.gov.uk/government/statistics/weekly-road-fuel-prices}{UK's
Government Data Page} and I will be using the price of Unleaded Petrol
for my analysis. I, then extracted data for Petrol in another file and
saved it as a csv file. The petrol prices in this data is based on the
average UK pump prices from six companies and recorded weekly. This data
starts from June 2003. The prices in the data set is in terms of pence.
(£1=100p)

\hypertarget{objective-of-this-project}{%
\subsubsection{Objective of this
project}\label{objective-of-this-project}}

By analysing this dataset, the main objective of this project is to seek
to understand the patterns and trends of Petrol prices in the UK over
time, and ultimately improve ability to forecast the price of Petrol in
the UK. I aim to I will be using Meta's Prophet library to model the
data.

\hypertarget{set-up-the-library}{%
\subsubsection{1. Set up the library}\label{set-up-the-library}}

I would like to first load the prophet in my library. To load it a
simple R-code has been written down:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(prophet)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'prophet' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: Rcpp
\end{verbatim}

\begin{verbatim}
## Warning: package 'Rcpp' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: rlang
\end{verbatim}

Prophet is a forecasting tool developed by Meta, which is designed to
simplify time series forecasting tasks. This will help us in analysing
the components of the price of Petrol over time and also forecast the
future prices .

\hypertarget{loading-the-data-into-the-r}{%
\subsubsection{2. Loading the data into the
R}\label{loading-the-data-into-the-r}}

Now, we try to load the data in the system.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fuel\_data}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/pkeni/OneDrive {-} Queen Mary, University of London/Petrol Price UK .csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now that I have loaded the data into R my next step would be converting
it into dataframe of prices and volumes. I am making sure that the data
reads through so I have converted them into Date and numeric form so
that prophet is able to fit it. Initially, I will also look at weekly
seasonality of the data as I want to identify recurring patterns to
exhibit distinct petrol price movements. Also, as the prices are
recorded on a weekly basis, I believe weekly seasonality would work the
best in this terms.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fuel\_data}\SpecialCharTok{$}\NormalTok{date}\OtherTok{\textless{}{-}}\FunctionTok{as.Date}\NormalTok{(fuel\_data}\SpecialCharTok{$}\NormalTok{Date)}
\NormalTok{fuel\_data}\SpecialCharTok{$}\NormalTok{Price}\OtherTok{\textless{}{-}}\FunctionTok{as.numeric}\NormalTok{(fuel\_data}\SpecialCharTok{$}\NormalTok{Price)}
\NormalTok{petrol\_price }\OtherTok{\textless{}{-}}\FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{ds=}\NormalTok{zoo}\SpecialCharTok{::}\FunctionTok{as.Date}\NormalTok{(fuel\_data}\SpecialCharTok{$}\NormalTok{Date),}
  \AttributeTok{y=}\NormalTok{fuel\_data}\SpecialCharTok{$}\NormalTok{Price)}
\end{Highlighting}
\end{Shaded}

\hypertarget{visualising-the-pettrol-price-data}{%
\subsubsection{3. Visualising the Pettrol Price
Data}\label{visualising-the-pettrol-price-data}}

In this section, I will simply just plot the petrol price solely based
in its historic price.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(petrol\_price}\SpecialCharTok{$}\NormalTok{ds,petrol\_price}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{main=}\StringTok{"Petrol Prices over year from 2003 to 2024"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Year"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"Petrol Prices (p per litre) "}\NormalTok{,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Coursework1_files/figure-latex/unnamed-chunk-5-1.pdf}

\hypertarget{decomposing-the-time-series-data}{%
\subsubsection{3. Decomposing the Time Series
Data}\label{decomposing-the-time-series-data}}

Now to further examine the time series, we tend to decompose the data.
As the data was loaded manually in R, I had some problem in decomposing
it to look at the trend, seasonality, cyclic patterns and residual noise
in the data. So, to decompose the data, I first convert it into a Time
Series Using function \textbf{ts()}. As I know that the original data
starts from 09 June 2003, I start the data from the very date and as it
is weekly I set the frequency of the Time Series to be 52.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fuel\_data\_ts}\OtherTok{\textless{}{-}}\FunctionTok{ts}\NormalTok{(fuel\_data}\SpecialCharTok{$}\NormalTok{Price,}\AttributeTok{start=}\FunctionTok{c}\NormalTok{(}\DecValTok{2003}\NormalTok{,}\DecValTok{06}\NormalTok{,}\DecValTok{09}\NormalTok{),}\AttributeTok{frequency=}\DecValTok{52}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

As the time series ``fuel\_data\_ts'' has been defined, now I decompose
the time series to see how it performs.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{decompose}\NormalTok{(fuel\_data\_ts))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Coursework1_files/figure-latex/unnamed-chunk-7-1.pdf}

We can see that the additive model has been fitted in the Time Series.
We can depict that the fuel price has an overall of increasing trend
across the time frame, with some kinks. We can also see that the noise
has increased over the last few months from 2022, which can be explained
because of the energy crisis in the UK. Overall, the data doesn't look
very noisy. The seasonality suggests that the changes in fuel prices
have been repeated at regular interval over time consistently.

\emph{Note: I have only used the fuel\_data\_ts here as it is
transformed into Time Series data type in R, in the other sections, i
will be using the petrol\_price data frame which I particularly defined
for prophet, as it has the recorded date from the dataset for
consistency and accuracy.}

\hypertarget{fitting-linear-trend-function-to-the-time-series}{%
\subsubsection{4. Fitting Linear Trend Function to the Time
Series}\label{fitting-linear-trend-function-to-the-time-series}}

I, now, will run a linear regression which will help me gain
understanding of the growth of the petrol prices in the UK. Here, I will
use the \textbf{lm} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(petrol\_price}\SpecialCharTok{$}\NormalTok{ds,petrol\_price}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{xlab=}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{, }\AttributeTok{ylab=}\StringTok{\textquotesingle{}Price of Petrol\textquotesingle{}}\NormalTok{, }\AttributeTok{main=}\StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{)}
\NormalTok{Linearmodel\_fuel}\OtherTok{=}\FunctionTok{lm}\NormalTok{(petrol\_price}\SpecialCharTok{$}\NormalTok{y}\SpecialCharTok{\textasciitilde{}}\NormalTok{petrol\_price}\SpecialCharTok{$}\NormalTok{ds,petrol\_price)}
\FunctionTok{lines}\NormalTok{(petrol\_price}\SpecialCharTok{$}\NormalTok{ds,}\FunctionTok{fitted}\NormalTok{(Linearmodel\_fuel), }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Coursework1_files/figure-latex/unnamed-chunk-8-1.pdf}

The trend line suggests an upward trend in the fuel price data. Though
the trend line doesn't define for the

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(Linearmodel\_fuel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = petrol_price$y ~ petrol_price$ds, data = petrol_price)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.741 -10.246  -3.642  10.395  49.887 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     -9.0597428  3.1404207  -2.885  0.00399 ** 
## petrol_price$ds  0.0078596  0.0001944  40.423  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 14.02 on 1082 degrees of freedom
## Multiple R-squared:  0.6016, Adjusted R-squared:  0.6013 
## F-statistic:  1634 on 1 and 1082 DF,  p-value: < 2.2e-16
\end{verbatim}

It is evident that the Residual Standard Error is 14.02, which means
that the model is in average 14.02 pence off while using this to predict
the fuel price. The multiple R squared value of 60.16\% suggests that
the 60.16\% of variability in the petrol prices can be explained by the
time in this model.

\hypertarget{fitting-the-data-into-prophet-model}{%
\subsubsection{5. Fitting the Data into Prophet
Model}\label{fitting-the-data-into-prophet-model}}

Now, I will fit the data frame (petrol.prices) into prophet to analyse
the data. This prophet function is used to fit the model. I won't use
daily seasonality as this data has been recorded weekly.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_price}\OtherTok{=}\NormalTok{prophet}\SpecialCharTok{::}\FunctionTok{prophet}\NormalTok{(petrol\_price,}\AttributeTok{weekly.seasonality =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
\end{verbatim}

The prophet model is an additive model with components such as trend,
seasonality, holidays and error terms.

\hypertarget{future-price-data-frame-setup}{%
\subsubsection{6. Future Price Data Frame
Setup}\label{future-price-data-frame-setup}}

Now that the model has been fitted using the prophet function, the
predictions are made on the dataframe, using the funtion
\textbf{make\_future\_dataframe}, this function takes the model object
and a number of periods to forecast to provide a suitable dataframe of
the dates.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{future\_price}\OtherTok{\textless{}{-}}\FunctionTok{make\_future\_dataframe}\NormalTok{(model\_price,}\AttributeTok{periods=}\DecValTok{52}\NormalTok{,}\AttributeTok{freq=}\StringTok{"week"}\NormalTok{)}
\FunctionTok{tail}\NormalTok{(future\_price)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              ds
## 1131 2025-02-03
## 1132 2025-02-10
## 1133 2025-02-17
## 1134 2025-02-24
## 1135 2025-03-03
## 1136 2025-03-10
\end{verbatim}

As, this project is based on a weekly dataset, the future predictions
are based will also be on weekly forecast for better accuracy, so I have
set the frequency to week. Here, the data frame is set such that it is
ready to forecast fuel prices weekly up-to a year.

\hypertarget{forecasting-the-future-prices}{%
\subsubsection{7. Forecasting the Future
Prices}\label{forecasting-the-future-prices}}

As the new data frame has been defined in chapter 6, here I will use the
dataframe defined to make future predictions of petrol prices. For this
I will use the function \textbf{predict}. This function is responsible
to make predictions from the results of different model fitting
functions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predict\_futureprice}\OtherTok{=}\FunctionTok{predict}\NormalTok{(model\_price,future\_price)}
\FunctionTok{tail}\NormalTok{(predict\_futureprice[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}ds\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}yhat\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}yhat\_lower\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}yhat\_upper\textquotesingle{}}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              ds     yhat yhat_lower yhat_upper
## 1131 2025-02-03 164.8446   154.2281   175.4786
## 1132 2025-02-10 165.1329   154.5370   174.3761
## 1133 2025-02-17 165.4222   154.5664   175.5435
## 1134 2025-02-24 165.8229   155.1507   176.1471
## 1135 2025-03-03 166.4607   155.7787   176.5944
## 1136 2025-03-10 167.3056   157.2822   178.0674
\end{verbatim}

The table above contains the predictions of the future petrol prices
weekly ranging from February 5,2025 to March 10, 2025, which is exactly
like a year far from now. It has the price predictions with their
associated confidence intervals, where \textbf{yhat\_lower} represents
the lower bound of the confidence interval whereas \textbf{Yhat\_upper}
represents the upper bound, and \textbf{yhat} represents the forecasted
price of petrol. The predictions during this specific time (form Feb
2025 to March) seem to vary between 164.84p/litre to 167.31p/litre, and
it is also noticeable that the price has an increasing trend with time
constraint.

\end{document}
